version: '3.7'

services:
  postgres:
    container_name: postgres-db
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=upload-cloudflarer2
    volumes:
      - postgres_data:/bitnami/postgresql
  
volumes:
  postgres_data:
