// Upload
POST http://localhost:3333/v1/uploads
content-type: application/json

{
  "name": "file.mp4",
  "contentType": "video/mp4"
}

### 

// Download - change the id
GET http://localhost:3333/v1/uploads/:id

